---
environment: development
domain: jerra.io

docker_env_variables:
  the_island:
    serverMap: TheIsland
    am_ark_SessionName: "Scrapps The Island Server"
    am_ark_ServerAdminPassword: "{{ enc_server_admin_password }}"
    am_ark_MaxPlayers: "10"
    am_ark_QueryPort: "27015"
    am_ark_Port: "7778"
    am_ark_RCONPort: "32330"
    am_arkwarnminutes: "60"
  ragnarok:
    serverMap: Ragnarok
    am_ark_SessionName: "Scrapps Ragnarok Server"
    am_ark_ServerAdminPassword: "{{ enc_server_admin_password }}"
    am_ark_MaxPlayers: "10"
    am_ark_QueryPort: "27016"
    am_ark_Port: "7780"
    am_ark_RCONPort: "32331"
    am_arkwarnminutes: "60"
  crystalisles:
    serverMap: CrystalIsles
    am_ark_SessionName: "Scrapps Crystal Isles Server"
    am_ark_ServerAdminPassword: "{{ enc_server_admin_password }}"
    am_ark_MaxPlayers: "10"
    am_ark_QueryPort: "27017"
    am_ark_Port: "7782"
    am_ark_RCONPort: "32332"
    am_arkwarnminutes: "60"
  nfs:
    NFS_EXPORT_0: "/mnt                 *(rw,fsid=0,no_root_squash,no_subtree_check)"
    NFS_EXPORT_1: "/mnt/theisland       *(rw,no_root_squash,no_subtree_check)"
    NFS_EXPORT_2: "/mnt/ragnarok        *(rw,no_root_squash,no_subtree_check)"
    NFS_EXPORT_3: "/mnt/crystalisles    *(rw,no_root_squash,no_subtree_check)"
    NFS_EXPORT_4: "/mnt/minecraft-data  *(rw,no_root_squash,no_subtree_check)"
    NFS_EXPORT_5: "/mnt/minecraft-mods  *(rw,no_root_squash,no_subtree_check)"

docker_port_maps:
  theisland:
    - { published_port: 7778, target_port: 7778, protocol: tcp }
    - { published_port: 7778, target_port: 7778, protocol: udp }
    - { published_port: 7777, target_port: 7777, protocol: tcp }
    - { published_port: 7777, target_port: 7777, protocol: udp }
    - { published_port: 27015, target_port: 27015, protocol: tcp }
    - { published_port: 27015, target_port: 27015, protocol: udp }
    - { published_port: 32330, target_port: 32330, protocol: tcp }
  ragnarok:
    - { published_port: 7780, target_port: 7780, protocol: tcp }
    - { published_port: 7780, target_port: 7780, protocol: udp }
    - { published_port: 7779, target_port: 7779, protocol: tcp }
    - { published_port: 7779, target_port: 7779, protocol: udp }
    - { published_port: 27016, target_port: 27016, protocol: tcp }
    - { published_port: 27016, target_port: 27016, protocol: udp }
    - { published_port: 32331, target_port: 32331, protocol: tcp }
  crystalisles:
    - { published_port: 7782, target_port: 7782, protocol: tcp }
    - { published_port: 7782, target_port: 7782, protocol: udp }
    - { published_port: 7781, target_port: 7781, protocol: tcp }
    - { published_port: 7781, target_port: 7781, protocol: udp }
    - { published_port: 27017, target_port: 27017, protocol: tcp }
    - { published_port: 27017, target_port: 27017, protocol: udp }
    - { published_port: 32332, target_port: 32332, protocol: tcp }
  nfs:
    - { published_port: 111, target_port: 111, protocol: tcp, mode: host }
    - { published_port: 111, target_port: 111, protocol: udp, mode: host }
    - { published_port: 2049, target_port: 2049, protocol: tcp, mode: host }
    - { published_port: 2049, target_port: 2049, protocol: udp, mode: host }
    - { published_port: 32765, target_port: 32765, protocol: tcp, mode: host }
    - { published_port: 32765, target_port: 32765, protocol: udp, mode: host }
    - { published_port: 32767, target_port: 32767, protocol: tcp, mode: host }
    - { published_port: 32767, target_port: 32767, protocol: udp, mode: host }
