---
hosts: all

tasks:

  #############################################################################
  # Installing docker ce
  - name: Add docker repo
    ansible.builtin.command:
      cmd: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  - name: Install docker-ce
    ansible.builtin.dnf:
      name: docker-ce
      state: present
    notify:
     - docker enable
     - docker start

  #############################################################################
  # Installing Puppet
  - name: Install puppet repository
    ansible.builtin.dnf:
      name: https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
      state: present
  - name: Install Puppet agent
    when: not inventory_hostname == "docker-storage.jerra.io" 
    ansible.builtin.dnf:
      when: inventory_hostname == "docker-storage.jerra.io" 
      name: puppet-agent
      state: present
  - name: Install Puppet Server
    ansible.builtin.dnf:
      name: puppetmaster
      state: present
