---
- name: Deploy Ark Ragnarok service
  hosts: node_master
  gather_facts: false
  tasks:

  - name: Create a network with options
    docker_network:
      name: gaming_overlay
      driver: overlay
      driver_options:
        encrypted: true

  - name: Create crystalisles_volume
    docker_volume:
      name: crystalisles_volume
      driver_options:
        type: nfs4
        device: :/crystalisles
        o: addr=192.168.1.50

  - name: Deploy Ark Crystal Isles service
    docker_swarm_service:
      name: crystalisles 
      hostname: crystalisles 
      image: thmhoag/arkserver
      env: "{{ docker_env_variables.crystalisles  }}"
      networks: gaming_overlay
      publish: "{{ docker_port_maps.crystalisles  }}"
      mounts:
      - source: crystalisles_volume
        target: /ark
        type: volume
      placement:
        constraints:
          - node.labels.node == general
