---
- name: Deploy Ark Ragnarok Volumes
  hosts: all:!node_master
  gather_facts: false
  tasks:

  - name: Create ragnarok_volume
    docker_volume:
      name: ragnarok_volume
      driver_options:
        type: nfs4
        device: :/ragnarok
        o: addr=192.168.1.50

- name: Deploy Ark Ragnarok service
  hosts: node_master
  gather_facts: false
  tasks:

  - name: Create a network with options
    docker_network:
      name: gaming_overlay
      driver: overlay
      driver_options:
        encrypted: true

  - name: Deploy Ark Ragnarok service
    docker_swarm_service:
      name: ragnarok
      hostname: ragnarok
      image: thmhoag/arkserver
      env: "{{ docker_env_variables.ragnarok }}"
      networks: gaming_overlay
      publish: "{{ docker_port_maps.ragnarok }}"
      mounts:
      - source: ragnarok_volume
        target: /ark
        type: volume
      placement:
        constraints:
          - node.labels.node == general
