---
hosts: node1

  tasks:

  - name: Create theisland_volume
    community.general.docker_volume:
      name: theisland_volume
      driver_options:
        type: nfs4
        device: :/theisland
        o: addr=192.168.1.50

  - name: Deploy theisland service
    community.general.docker_swarm_service:
      name: theisland
      hostname: theisland
      image: thmhoag/arkserver
      env: "{{ docker_env_variables.the_island }}"
      publish: "{{ docker_port_maps.the_island }}"
      endpoint_mode: dnsrr
      mounts:
        source: theisland_volume
        target: /ark
        type: volume
